server:
  port: 9004
spring:
  main:
    web-application-type: reactive
  application:
    name: api-gateway
  zipkin:
    base-url: http://localhost:9411
  cloud:
    gateway:
      routes:
        - id: customer
          uri: lb://CUSTOMER
          predicates:
            - Path=/api/v1/customers/**
  boot:
    admin:
      client:
        url: http://localhost:9080
logging:
  file:
    name: apigw.log
    max-history: 5
    max-size: 10MB

management:
  endpoints:
    web:
      exposure:
        include: "*"
    health:
      show-details: always

eureka:
  client:
    service-url:
      defaultZone: http://localhost:9000/eureka
    fetch-registry: true
    register-with-eureka: true